### ISSUE TITLE
プルリクエスト発行時の Github Actions の実行

### ISSUE THREAD

**Issue by Osmium1008** [TKPaken/beginners#113]
プルリクエストを発行した時にそのコードのビルドが可能かなどを確認できるようにしたい。

**Comment by Osmium1008** [comment]
今回みたいなことないように本当にこれやっておくべきなのでは...と思っていたりします

**Comment by ageprocpp** [comment]
successfully に Actions は実行されてるから，エラーハンドリングの方法が目視になっちゃうと思うんだけど，これなんか自動化できるんですか

**Comment by 0xdef12e** [comment]
無理があろうかと思われます

**Comment by ageprocpp** [comment]
というか，たとえエラー出るまま push されても deploy されないだけだから，正直困らないんだよね（まあテストの実行くらいなら入れてもいいと思うけど）

**Comment by Osmium1008** [comment]
あー なるほど...

**Comment by ageprocpp** [comment]
ということで，まあやるなら Osmium くん適当にやってください　やらないなら issue 閉めちゃって良さそう
