### ISSUE TITLE
記事名の表示

### ISSUE THREAD

**Issue by Osmium1008** [TKPaken/beginners#27]
記事"Windowsでの環境構築(Visual Studio)"にてタイトルがVisualまでで切られてしまう。

**Comment by defineProgram** [comment]
![image](https://user-images.githubusercontent.com/47498872/77720248-b8d31500-702a-11ea-9969-02af5e41c5df.png)
どこのことか分からんけど起きてなさそうに見える

**Comment by Osmium1008** [comment]
下

**Comment by defineProgram** [comment]
これは、previewの単語数の問題
一切問題ない

**Comment by defineProgram** [comment]
まあ、フォーマットを統一してからtruncate wordsをいくつにするか考えると思う
日本語だと空白あんまり空けないから、少なめにしないとごちゃごちゃするんだよね

**Comment by Osmium1008** [comment]
h1だけ抽出とか出来ませんか

**Comment by defineProgram** [comment]
多分最初の単語3つ、とかにすると思うけど
h1だけ抽出しても、どうせタイトルだし変わんなくね（題名のフォーマット変わる予定だし）

**Comment by Osmium1008** [comment]
それだとそもそもプレビューある必要なさそう...

**Comment by defineProgram** [comment]
3単語つっても、割と量あるからね？日本語だから（ここまで1単語）

**Comment by capra314cabra** [comment]
VisualStudioって表記にそこだけするという禁じ手を使用するしかなさそう

**Comment by defineProgram** [comment]
別に柔軟性はあるので、気にする必要はありません
