### ISSUE TITLE
Chapter3*2

### ISSUE THREAD

**Issue by Osmium1008** [TKPaken/beginners#37]
chapter3が初期からあると思われるものと新しいものの２つが混在している。(どちらを残せばいいかがわからないので修正は担当の人に任せます...)

**Comment by autumn-eel** [comment]
2つめはAPG4bについて書きます

**Comment by Osmium1008** [comment]
あー(3.1,3.2のように見た目でのタイトル分けたほうが良い気がしますが...)

**Comment by autumn-eel** [comment]
そうですね APG4bのページ書いたらやっておきます
